### PR TITLE
clean up the sbt files for community build

### PR DESCRIPTION
**Pull request by fommil**
working towards #180

### CODE REVIEW

**Comment by fommil** [comment]
```
[error] Failed: Total 1477, Failed 18, Errors 0, Passed 1390, Skipped 69
[error] Failed tests:
[error] 	scala.tools.refactoring.tests.sourcegen.PrettyPrinterTest
[error] 	scala.tools.refactoring.tests.sourcegen.SourceGenTest
[error] 	scala.tools.refactoring.tests.implementations.imports.OrganizeImportsTest
[error] 	scala.tools.refactoring.tests.implementations.ExplicitGettersSettersTest
[error] 	scala.tools.refactoring.tests.implementations.imports.AddImportStatementTest
```

**Comment by fommil** [comment]
@adriaanm https://github.com/scala/scala/commit/fe2d7ff6821bcd0bf413b03c1c211b488a230fbe broke all the things :crying_cat_face:

**Comment by fommil** [comment]
I'm seeing `finishDocComment` being called a lot without `beginDocComment` having been called

**Comment by adriaanm** [comment]
Does registerDocComment work for you? You shouldn't have to override the
other ones.

**Comment by adriaanm** [comment]
See https://github.com/typesafehub/genjavadoc/pull/94

**Comment by fommil** [comment]
thanks for responding! `registerDocComment` was what I tried in the first place but it is never called. The test I'm iterating on most (because it seems directly affected) is `scala.tools.refactoring.tests.implementations.imports.OrganizeImportsTest` incase anybody is able to also try.

I'll be spending all day tomorrow on this.

**Comment by fommil** [comment]
I've pushed my version with the `registerDocComment`. Nothing ever appears on stdout. You can see my experiments below that in comments.

**Comment by fommil** [comment]
maybe the scala-refactoring `scan()` hack is the cause of this. I'll try with using `parse`

**Comment by adriaanm** [comment]
Thanks for working on this! We compile this project as part of the community build (https://github.com/scala/community-builds/blob/2.12.x/community.dbuild#L762) -- pity the regression wasn't caught by that.

**Comment by SethTisue** [comment]
> We compile this project as part of the community build (https://github.com/scala/community-builds/blob/2.12.x/community.dbuild#L762) -- pity the regression wasn't caught by that

doh! but it will be next time: https://github.com/scala/community-builds/issues/461

**Comment by mlangc** [comment]
We could easily get rid of the brittle dependency altogether, as it is used in `scala.tools.refactoring.implementations.oimports.RegionBuilder.scanForComments[G](global: G)(source: SourceFile)` only, where we could replace it with (I've just tested this)

```scala
  def comments(source: SourceFile): List[RangePosition] = {
    import scala.tools.refactoring.util.SourceWithMarker
    import scala.tools.refactoring.util.SourceWithMarker.Movements._

    val commentWithNewline = comment ~ '\n'.optional

    @tailrec
    def doWork(srcWithMarker: SourceWithMarker, acc: List[RangePosition] = Nil): List[RangePosition] = {
      if (srcWithMarker.isDepleted) {
        acc
      } else {
        srcWithMarker.applyMovement(commentWithNewline) match {
          case Some(srcAfterComment) =>
            val (commentStart, commentEnd) = (srcWithMarker.marker, srcAfterComment.marker)
            val commentRange = new RangePosition(source, commentStart, commentStart, commentEnd)
            doWork(srcAfterComment, commentRange :: acc)

          case None =>
            doWork(srcWithMarker.stepForward, acc)
        }
      }
    }

    doWork(SourceWithMarker(source.content)).reverse
  }
```

**Comment by fommil** [comment]
:smile: I'll be able to check in an hour or so.

**Comment by fommil** [comment]
(if you have a PR in the meantime, I won't stop you!)

**Comment by mlangc** [comment]
Already working on it :-)

**Comment by mlangc** [comment]
See https://github.com/scala-ide/scala-refactoring/pull/183

**Comment by fommil** [comment]
reworking the purpose of this PR in light of the awesome #183

**Comment by sschaef** [comment]
add to whitelist

**Pull request merged**
