### PR TITLE
fixes import tests

### PR DESCRIPTION
**Pull request by fommil**
fix for change in behaviour of https://github.com/scala/scala/pull/5330

### CODE REVIEW

**Comment by fommil** [comment]
tests that remain are

```
[error] Failed: Total 1477, Failed 12, Errors 0, Passed 1396, Skipped 69
[error] Failed tests:
[error] 	scala.tools.refactoring.tests.sourcegen.PrettyPrinterTest
[error] 	scala.tools.refactoring.tests.sourcegen.SourceGenTest
[error] 	scala.tools.refactoring.tests.implementations.ExplicitGettersSettersTest
```

**Comment by sschaef** [comment]
the fix is good enough I guess

**Comment by fommil** [comment]
yeah, disgusting to use exceptions for control flow but I couldn't think of another way that is compatible with all versions of scala

**Comment by som-snytt** [comment]
I don't know about the compatibility question, but I see the question is how to determine if the next line is nonEmpty. You can just inch forward until you're on the next line or EOF, then get if that line is empty.

Also there is a kludge whereby NL is added if content doesn't end in whitespace; there's a comment that it's so token.pos.end is a valid index. So there is no empty file.

I don't think I understood how the reporter of SI-9885 was counting lines -- my eclipse-using colleague and I had this convo again recently -- if the text ends in NL, is there an empty line after that? I already let him have his way with tabs, because he is French and a traditionalist.

```
$ scala
Welcome to Scala 2.12.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_111).
Type in expressions for evaluation. Or try :help.

scala> import scala.reflect.internal.util._
import scala.reflect.internal.util._

scala> implicit class t184(val pos: Position) {
     | def isNextLineNonEmpty: Boolean = {
     |   val startAt = pos.source.lineToOffset(pos.line - 1) + pos.lineContent.length
     |   (startAt until pos.source.content.length).find(i => Position.offset(pos.source, i).line > pos.line).map(
     |   i => !Position.offset(pos.source, i).lineContent.isEmpty).getOrElse(false)
     | }}
defined class t184
```
so
```
scala> val f = new BatchSourceFile("test", "abc\ndef  ")
f: scala.reflect.internal.util.BatchSourceFile = test

scala> val p = Position.offset(f, 0)
p: scala.reflect.internal.util.Position = source-test,line-1,offset=0

scala> p.isNextLineNonEmpty
res0: Boolean = true

scala> val f = new BatchSourceFile("test", "abc\n\ndef  ")
f: scala.reflect.internal.util.BatchSourceFile = test

scala> val p = Position.offset(f, 0)
p: scala.reflect.internal.util.Position = source-test,line-1,offset=0

scala> p.isNextLineNonEmpty
res1: Boolean = false

scala> val f = new BatchSourceFile("test", "abc")
f: scala.reflect.internal.util.BatchSourceFile = test

scala> val p = Position.offset(f, 0)
p: scala.reflect.internal.util.Position = source-test,line-1,offset=0

scala> p.isNextLineNonEmpty
res2: Boolean = false

scala> val f = new BatchSourceFile("test", "")
f: scala.reflect.internal.util.BatchSourceFile = test

scala> val p = Position.offset(f, 0)
p: scala.reflect.internal.util.Position = source-test,line-1,offset=0

scala> p.isNextLineNonEmpty
res3: Boolean = false

scala> 

scala> val f = new BatchSourceFile("test", "abc\r\n\r\ndef  ")
f: scala.reflect.internal.util.BatchSourceFile = test

scala> Position.offset(f, 0).isNextLineNonEmpty
res4: Boolean = false

```

**Pull request merged**
