### PR TITLE
Rename PimpedTrees to EnrichedTrees

### PR DESCRIPTION
**Pull request by thisfred**
addresses issue #134

### CODE REVIEW

**Comment by thisfred** [comment]
I have run sbt compile and sbt test, and both seem happy. Let me know if there are other checks I should perform.

**Comment by fommil** [comment]
LGTM, I assume you did a `git grep pimp` to find any leftovers?

**Comment by thisfred** [comment]
I did, there are only two references left, in the latex docs:

https://github.com/scala-ide/scala-refactoring/blob/master/src/doc/latex/thesis/2_refactoring_library.tex#L948
https://github.com/scala-ide/scala-refactoring/blob/master/src/doc/latex/thesis/thesis.tex#L1937

I did not feel comfortable changing that because: a) it's not code but someone's thesis (though I did change the code references in there.) and b) I don't know if the pattern mentioned is actually a widely known thing, but I have no idea what I'd change it to.

**Comment by sschaef** [comment]
add to whitelist

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
Please revert the changes in the tex files, they are outdated and we are going to move them to a different place soon.

**Comment by sschaef** [comment]
This PR breaks source compatibility but I guess that it isn't much of a use if we introduce a deprecated `trait PimpedTrees extends EnirchedTrees`. Beside from scala-ide and scalariform I don't know any users of scala-refactoring. I'm going to do the changes in scala-ide, there is only on usage anyway.

**Comment by fommil** [comment]
**cough** and ENSIME! :-P

**Comment by sschaef** [comment]
Also not difficult: ;)
```
[antoras@wookypooky → /tmp/ensime-server on master]
% ag "\bpimp"
core/src/main/scala/org/ensime/core/StructureViewBuilder.scala
9:import scala.tools.refactoring.common.{ CompilerAccess, PimpedTrees }

core/src/main/scala/org/ensime/core/SemanticHighlighting.scala
12:import scala.tools.refactoring.common.{ CompilerAccess, PimpedTrees }
16:class SemanticHighlighting(val global: RichPresentationCompiler) extends CompilerAccess with PimpedTrees {
```

for scala-ide:
```
[antoras@wookypooky → ~/dev/scala/scala-ide on master]
% ag "\bpimp"                                                                                                                                                                                                      M
org.scala-ide.sdt.core/src/org/scalaide/core/internal/decorators/semantichighlighting/classifier/SafeSymbol.scala
5:import scala.tools.refactoring.common.PimpedTrees
32:private[classifier] trait SafeSymbol extends CompilerAccess with PimpedTrees {
```

**Comment by fommil** [comment]
yeah, it's trivial for us, I think you'd asked earlier... but since you've basically been commenting / closing / moving about a bajillion tickets today, I'll let you off :stuck_out_tongue:

**Comment by sschaef** [comment]
I guess, I'm close in making a new record on how many emails I sent on a single day. ;)

**Comment by thisfred** [comment]
Reverted the changes to the tex files, and force pushed.

**Comment by sschaef** [comment]
The PR against scala-ide is here: https://github.com/scala-ide/scala-ide/pull/1069

**Comment by sschaef** [comment]
LGTM

**Comment by SethTisue** [comment]
I'm glad to see this change get in. but note that it has caused https://github.com/scala/scala-dev/issues/87

**Pull request merged**
