### PR TITLE
Adapts scala-refactoring library for scala 2.12

### PR DESCRIPTION
**Pull request by wpopielarski**

### CODE REVIEW

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
There was a test failure on 2.11.7. I updated the CI build to 2.11.8, where the test passes. I guess 2.11.7 compatibility is no longer needed, we can ignore it. scoverage plugin is not compatible with 2.12 yet. We never needed it anyway. Please remove the scoverage plugin completely. I don't think we will ever use it.

**Comment by wpopielarski** [comment]
@sschaef not sure what to do next?

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
Jenkins uses an outdated version of Java. I sent Luc a message.

**Comment by wpopielarski** [comment]
thanks Simon!

2016-12-12 12:19 GMT+01:00 Simon Schäfer <notifications@github.com>:

**Comment by wpopielarski** [comment]
so probably we can revert scoverage back.

2016-12-12 13:59 GMT+01:00 Wieslaw Popielarski <wpopielarski@gmail.com>:

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
Finally, all tests passed. LGTM. Did you add all changes that you wanted to make for support of 2.12.0 (title is still marked with WIP)?

**Comment by wpopielarski** [comment]
I restored scoverage plugin, now is ripe to be taken

**Pull request merged**
