### PR TITLE
Prepare for 0.7.0 release

### PR DESCRIPTION
**Pull request by sschaef**
Anything missing? Anything else you would like to see to change?

### CODE REVIEW

**Comment by misto** [comment]
What do you think, if we removed the examples as well (they're really old, probably don't compile anymore), we could also eliminate the .library folder by moving its content to the root?

**Comment by sschaef** [comment]
I would have nothing against it.

**Comment by misto** [comment]
Good :-)

**Comment by sschaef** [comment]
Is there any need to also keep two builds. I could also look into removing one of them (preferable the maven one). It is used in uber-build but it is no problem to change that. I guess the PR builder also needs to be updated.

**Comment by misto** [comment]
Good question, I'm not sure. Are there any benefits from Maven when using Eclipse?

**Comment by sschaef** [comment]
On 09/02/2015 09:55 PM, Mirko Stocker wrote:
>
> Good question, I'm not sure. Are there any benefits from Maven when 
> using Eclipse?
>
I don't know. Let's keep it for now. It works and I'm not interested in 
updating uber-build anyway. ;)

**Comment by sschaef** [comment]
I did the mentioned refactorings. Please have a look at the new pom file. I actually merged the contents of the root pom with the one in the removed directory, but I'm not sure if if all the stuff is really needed.

**Comment by misto** [comment]
I think we need to keep the old bundle name if we don't want to break all clients:
```
diff --git a/META-INF/MANIFEST.MF b/META-INF/MANIFEST.MF
index ff92667..a4b69bc 100644
--- a/META-INF/MANIFEST.MF
+++ b/META-INF/MANIFEST.MF
@@ -1,7 +1,7 @@
 Manifest-Version: 1.0
 Bundle-ManifestVersion: 2
 Bundle-Name: Scala Refactoring
-Bundle-SymbolicName: org.scala-refactoring
+Bundle-SymbolicName: org.scala-refactoring.library
 Bundle-Version: 0.7.0.qualifier
 Require-Bundle: org.junit;bundle-version="4.11.0",
  org.scala-lang.scala-library
diff --git a/pom.xml b/pom.xml
index b05cd48..2996b58 100644
--- a/pom.xml
+++ b/pom.xml
@@ -3,14 +3,14 @@
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <modelVersion>4.0.0</modelVersion>
   <groupId>org.scala-refactoring</groupId>
-  <artifactId>org.scala-refactoring</artifactId>
+  <artifactId>org.scala-refactoring.library</artifactId>
   <parent>
     <groupId>org.sonatype.oss</groupId>
     <artifactId>oss-parent</artifactId>
     <version>7</version>
   </parent>
   <version>0.7.0-SNAPSHOT</version>
-  <packaging>pom</packaging>
+  <packaging>eclipse-plugin</packaging>
   <name>Scala Refactoring Library</name>
   <url>http://scala-refactoring.org</url>
   <licenses>
```

I've built and diffed the results of the maven and the sbt build, and I think they're good.

**Comment by sschaef** [comment]
Oh yes, I didn't think about that. What about the `eclipse-plugin` packaging, do we need that? I guess not since it is no longer a Eclipse plugin but I don't know what exactly this property is doing.

**Comment by misto** [comment]
I guess setting that to `jar` would work as well, but if we use eclipse-plugin we still get a proper bundle (with the OSGI-Manifest etc.). To be safe, I'd vote to leave it as eclipse-plugin for now and in a later step when we get rid of all maven stuff wen can drop it anway.

**Comment by sschaef** [comment]
All remarks resolved.

**Comment by sschaef** [comment]
I updated the README a little bit. It now contains a section about how to publish. The section about the project layout is removed since it is no longer needed.

**Comment by misto** [comment]
It looks much cleaner now, thanks a lot Simon!

**Pull request merged**
