### PR TITLE
Remove maven build

### PR DESCRIPTION
**Pull request by sschaef**
@mlangc Would you please have a look at this? Is the sbt build working in the way how you would expect it? Also, I updated the `patch-ide.bash` script, is it still working correctly?

### CODE REVIEW

**Comment by sschaef** [comment]
We can keep the maven build alive for a few more week to test if it behaves similar to the sbt build.

**Comment by mlangc** [comment]
Apart from that, updating the IDE with the script works as it did before, with the Maven build. Will it also be possible to patch the IDE like this after the IDE build has been migrated to use the SBT build?

**Comment by sschaef** [comment]
On 29.12.2015 16:22, Matthias Langer wrote:
>
> Apart from that, updating the IDE with the script works as it did 
> before, with the Maven build. Will it also be possible to patch the 
> IDE like this after the IDE build has been migrated to use the SBT build?
>
Sure, the IDE already depends on the sbt build of scala-refactoring.

**Comment by sschaef** [comment]
Alright, uber-build and scala-ide don't rely on the maven build anymore. I hope there is no one else who is doing it because I'm killing it now. The sbt driven PR builds on Jenkins produced the same results as the maven driven ones. I hope there is no flaky behavior there anymore.

**Comment by misto** [comment]
:+1:

**Comment by SethTisue** [comment]
Great to see this crossing the finish line.

**Pull request merged**
